#!/usr/bin/perl

my $inputfile;
my @sentences;
my @palindromes;
my $longest ="";
my $longestP ="";
my $pcount = 0;

sub isPalindrome {
	my ($str) = @_;

	if($str eq reverse($str)){
		return 1;
	}
	else {
		return 0;
	}
}


open( my $inputfile,'input.txt') or die "Could not open $!";
	my $counter = 0;
	while (my $line = <$inputfile>) {
		$temp = "";
		chomp($line);
		$sentences[$counter] = $line;
#		print("$counter: $sentences[$counter]\n"); #debug
		if(length($sentences[$counter]) > length($longest)){
			$longest = $sentences[$counter];
		}

		$temp =	$sentences[$counter];
		$temp =~ s/ //g;
		$temp =~ s/[[:punct:]]//g;
		$temp = lc $temp;
#		print("$temp"); #debug

		if(isPalindrome($temp)){
			if(length($temp) > length($longestP)){
				$longestP = $sentences[$counter];
			}
			$pcount++;
		}

		$counter++;
	}

close $inputfile;

print("Longest sentence: \"$longest\"\n\n");
print("Number of palindromes: $pcount\n\n");
print("Longest Palindrome: \"$longestP\"\n\n");
