#!/usr/bin/perl

my $inputfile;
my @sentences;
my $longest ="";
my $longestP ="";
my $pcount = 0;

#subroutine that checks for palindrome conditions
sub isPalindrome {
	my ($str) = @_;

	if($str eq reverse($str)){
		return 1;
	}
	else {
		return 0;
	}
}

#start of main program

open( my $inputfile,'input.txt') or die "Could not open $!";
	my $counter = 0;
	while (my $line = <$inputfile>) {
		$temp = "";
		chomp($line); #removes newline char
		$sentences[$counter] = $line;
#		print("$counter: $sentences[$counter]\n"); #debug
		if(length($sentences[$counter]) > length($longest)){
			$longest = $sentences[$counter];
		}

		#format the string to prepare for palindrome condition checking
		$temp =	$sentences[$counter];
		$temp =~ s/ //g; #replaces spaces with nothing
		$temp =~ s/[[:punct:]]//g; #replaces punctuation with nothing
		$temp = lc $temp; #sets all chars to lowercase
#		print("$temp"); #debug

		if(isPalindrome($temp)){
			if(length($temp) > length($longestP)){
				$longestP = $sentences[$counter];
			}
			$pcount++;
		}

		$counter++;
	}

close $inputfile;

print("Longest sentence: \"$longest\"\n\n");
print("Number of palindromes: $pcount\n\n");
print("Longest Palindrome: \"$longestP\"\n\n");
